# services:
#   postgres_db:
#     image: postgres:latest
#     container_name: PostgresCont
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres123
#       - POSTGRES_DB=ccdb
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgres_data:/var/lib/postgresql/data

#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: ExpressCont
#     restart: always
#     environment:
#       - DBUSER=postgres
#       - DBPASSWORD=postgres123
#       - DBNAME=ccdb
#       - DBHOST=postgres_db # 👈 important: use the service name, NOT localhost
#       - DBPORT=5432
#     ports:
#       - "5001:5050" # host:container (change if needed)
#     depends_on:
#       - postgres_db
